Fix libvirtd_opts when using systemd
You see the following error when using puppet:
Error: Could not start Service[libvirt]: Execution of '/bin/systemctl
start libvirt-bin' returned 1: Job for libvirt-bin.service failed
because the control process exited with error code. See "systemctl
status libvirt-bin.service" and "journalctl -xe" for details.

This is because you cannot start the libvirt-bin service twice in a row.

root@pkvmci829:~# systemctl start libvirt-bin
root@pkvmci829:~# systemctl start libvirt-bin
Job for libvirt-bin.service failed because the control process exited
with error code. See "systemctl status libvirt-bin.service" and
"journalctl -xe" for details.

Systemd already is able to start libvirtd as a daemon.  It does not need
the -d parameter added to /etc/default/libvirt-bin.  This just causes
systemd to keep respawning libvirtd in a loop until it realizes that it
isn't working.

Change-Id: Iaffe85dda5c5bfed88f27602189aca074ec7aeda